name: maven-build-example
on:
  push:
    branches: 
      - 'feature/cicd'
jobs:
  say-hello:
    runs-on: sabareesh-asus
    steps:
      - name: clone replo
        uses: actions/checkout@v3
      - name: verfiy maven
        run: mvn -version
      - name: Setup Jdk 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Cache
        uses: actions/cache@v4.2.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            {{ runner.os }}-m2
      - name: maven build
        run: mvn clean install
      - name: check DNS resolution
        run: nslookup google.com
      - name: test http connectivity
        run: curl -I http://192.168.29.77:9000
      - name: Run tests
        run: mvn test 
      - name: Test SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl -v -u ${{ env.SONAR_TOKEN }}: http://192.168.29.77:9000/api/user_tokens/search
      - name: sonar build
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_URL: ${{ secrets.SONAR_URL }}
        run: mvn clean verify sonar:sonar -Dsonar.host.url=${{ secrets.SONAR_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        
