name: Java CI with  k8 workflow

on:
  push:
    branches:
      - cicd
      
      
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: clone the replo
        uses: actions/checkout@v3
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - name: verfiy maven
        run: mvn -version
      - name: Setup Jdk 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Cache
        uses: actions/cache@v4.2.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            {{ runner.os }}-m2
      - name: maven build
        run: mvn clean install
      - name: Run tests
        run: mvn test
      - name: sonar build
        uses: exo-actions/sonarcloud-action@1.0.0
        with:
         maven_version: 3.8.2
         jdk_major_version: 11
    # OpenJDK Adopted Distribution (temurin, zulu, adopt, liberica,...)
         jdk_distribution: temurin
         SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      - name: maven package 
        run: mvn clean package
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Images
        run: |
          docker build -t borigisabareesh/mvn-web-app:${{ github.sha }} .
      - name: Push Docker Images
        run: |
          docker push borigisabareesh/mvn-web-app:${{ github.sha }}
      - name: check pwd
        run: ls
      - name: Update deployment tag
        run: |
          sed -i 's~borigisabareesh/mvn-web-app:[^"]*~borigisabareesh/mvn-web-app:${{ github.sha }}~' mavenwebappdeployment.yaml
          cat mavenwebappdeployment.yaml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add mavenwebappdeployment.yaml
          git commit -m "Update deployment tag in mavenwebappdeployment.yaml"
          git push

      - name: Verify updated file
        run: cat mavenwebappdeployment.yaml
      - name: debug issue
        run: echo ${HOME} && pwd
      - name: Create kubeconfig
        run: |
          mkdir -p ${HOME}/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
          cat ${HOME}/.kube/config
      - name: Use context
        run: kubectl config use-context kind-samplemicroservice
      - name: Deploy to K8s
        run: kubectl apply -f mavenwebappdeployment.yaml
      - name: verify pods
        run: kubectl get pods
